"use server";

export interface SubnetLiquidityPoolParams {
    tokenAContractId: string;
    tokenBContractId: string;
    poolName: string;
    lpTokenSymbol: string;
    swapFee: number;
    rebate: number;
    enableLimitOrders?: boolean;
    enableDCA?: boolean;
    enablePerps?: boolean;
}

export async function generateSubnetLiquidityPool(params: SubnetLiquidityPoolParams) {
    // Base contract code template from x-vault.clar but with parameters
    const code = `
;; Title: ${params.poolName}
;; Version: 1.0.0
;; Description: 
;;   Implementation of the standard trait interface for liquidity pools on the Stacks blockchain.
;;   Provides automated market making functionality between two SIP-010 compliant tokens.
;;   Implements SIP-010 fungible token standard for LP token compatibility.
;;   Generated by Charisma Launchpad

;; Traits
(impl-trait 'SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1.sip010-ft-trait)
(impl-trait 'SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.dexterity-traits-v0.liquidity-pool-trait)

;; Constants
(define-constant DEPLOYER tx-sender)
(define-constant CONTRACT (as-contract tx-sender))
(define-constant ERR_UNAUTHORIZED (err u403))
(define-constant ERR_INVALID_OPERATION (err u400))
(define-constant PRECISION u1000000)
(define-constant LP_REBATE u${params.rebate})

;; Opcodes
(define-constant OP_SWAP_A_TO_B 0x00)      ;; Swap token A for B
(define-constant OP_SWAP_B_TO_A 0x01)      ;; Swap token B for A
(define-constant OP_ADD_LIQUIDITY 0x02)    ;; Add liquidity
(define-constant OP_REMOVE_LIQUIDITY 0x03) ;; Remove liquidity
(define-constant OP_LOOKUP_RESERVES 0x04)  ;; Read pool reserves

;; Define LP token
(define-fungible-token ${params.lpTokenSymbol})
(define-data-var token-uri (optional (string-utf8 256)) none)

;; --- SIP10 Functions ---

(define-public (transfer (amount uint) (sender principal) (recipient principal) (memo (optional (buff 34))))
    (begin
        (asserts! (is-eq tx-sender sender) ERR_UNAUTHORIZED)
        (try! (ft-transfer? ${params.lpTokenSymbol} amount sender recipient))
        (match memo to-print (print to-print) 0x0000)
        (ok true)))

(define-read-only (get-name)
    (ok "${params.poolName}"))

(define-read-only (get-symbol)
    (ok "${params.lpTokenSymbol}"))

(define-read-only (get-decimals)
    (ok u6))

(define-read-only (get-balance (who principal))
    (ok (ft-get-balance ${params.lpTokenSymbol} who)))

(define-read-only (get-total-supply)
    (ok (ft-get-supply ${params.lpTokenSymbol})))

(define-read-only (get-token-uri)
    (ok (var-get token-uri)))

(define-public (set-token-uri (uri (string-utf8 256)))
    (if (is-eq contract-caller DEPLOYER)
        (ok (var-set token-uri (some uri))) 
        ERR_UNAUTHORIZED))

;; --- Core Functions ---

(define-public (swap-a-to-b (amount uint))
    (let (
        (sender tx-sender)
        (delta (get-swap-quote amount (some OP_SWAP_A_TO_B))))
        ;; Transfer token A to pool
        (try! (contract-call? '${params.tokenAContractId} transfer amount sender CONTRACT none))
        ;; Transfer token B to sender
        (try! (as-contract (contract-call? '${params.tokenBContractId} transfer (get dy delta) CONTRACT sender none)))
        (ok delta)))

(define-public (swap-b-to-a (amount uint))
    (let (
        (sender tx-sender)
        (delta (get-swap-quote amount (some OP_SWAP_B_TO_A))))
        ;; Transfer token B to pool
        (try! (contract-call? '${params.tokenBContractId} transfer amount sender CONTRACT none))
        ;; Transfer token A to sender
        (try! (as-contract (contract-call? '${params.tokenAContractId} transfer (get dy delta) CONTRACT sender none)))
        (ok delta)))

(define-public (add-liquidity (amount uint))
    (let (
        (sender tx-sender)
        (delta (get-liquidity-quote amount)))
        (try! (contract-call? '${params.tokenAContractId} transfer (get dx delta) sender CONTRACT none))
        (try! (contract-call? '${params.tokenBContractId} transfer (get dy delta) sender CONTRACT none))
        (try! (ft-mint? ${params.lpTokenSymbol} (get dk delta) sender))
        (ok delta)))

(define-public (remove-liquidity (amount uint))
    (let (
        (sender tx-sender)
        (delta (get-liquidity-quote amount)))
        (try! (ft-burn? ${params.lpTokenSymbol} (get dk delta) sender))
        (try! (as-contract (contract-call? '${params.tokenAContractId} transfer (get dx delta) CONTRACT sender none)))
        (try! (as-contract (contract-call? '${params.tokenBContractId} transfer (get dy delta) CONTRACT sender none)))
        (ok delta)))

;; --- Subnet Functions ---

(define-public (x-add-liquidity (amount uint) 
    (signature-a (buff 65)) (uuid-a (string-ascii 36)) 
    (signature-b (buff 65)) (uuid-b (string-ascii 36)))
    (let (
        (delta (get-liquidity-quote amount))
        (amount-a (get dx delta))
        (amount-b (get dy delta))

        (signer-a (try! (contract-call? 'SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.blaze-rc10 recover signature-a
            '${params.tokenAContractId} "TRANSFER_TOKENS" none (some amount-a) (some CONTRACT) uuid-a)))

        (signer-b (try! (contract-call? 'SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.blaze-rc10 recover signature-b
            '${params.tokenBContractId} "TRANSFER_TOKENS" none (some amount-b) (some CONTRACT) uuid-b))))

        (try! (contract-call? '${params.tokenAContractId} x-transfer signature-a amount-a uuid-a CONTRACT))
        (try! (contract-call? '${params.tokenBContractId} x-transfer signature-b amount-b uuid-b CONTRACT))
        (try! (ft-mint? ${params.lpTokenSymbol} (/ (get dk delta) u2) signer-a))
        (try! (ft-mint? ${params.lpTokenSymbol} (/ (get dk delta) u2) signer-b))
        (ok delta)))

;; --- Helper Functions ---

(define-private (get-byte (opcode (optional (buff 16))) (position uint))
    (default-to 0x00 (element-at? (default-to 0x00 opcode) position)))

(define-private (get-reserves)
    { 
      a: (unwrap-panic (contract-call? '${params.tokenAContractId} get-balance CONTRACT)), 
      b: (unwrap-panic (contract-call? '${params.tokenBContractId} get-balance CONTRACT))
    })

;; --- Quote Functions ---

(define-read-only (get-swap-quote (amount uint) (opcode (optional (buff 16))))
    (let (
        (reserves (get-reserves))
        (operation (get-byte opcode u0))
        (is-a-in (is-eq operation OP_SWAP_A_TO_B))
        (x (if is-a-in (get a reserves) (get b reserves)))
        (y (if is-a-in (get b reserves) (get a reserves)))
        (dx (/ (* amount (- PRECISION LP_REBATE)) PRECISION))
        (numerator (* dx y))
        (denominator (+ x dx))
        (dy (/ numerator denominator)))
        {
          dx: dx,
          dy: dy,
          dk: u0
        }))

(define-read-only (get-liquidity-quote (amount uint))
    (let (
        (k (ft-get-supply ${params.lpTokenSymbol}))
        (reserves (get-reserves)))
        {
          dx: (if (> k u0) (/ (* amount (get a reserves)) k) amount),
          dy: (if (> k u0) (/ (* amount (get b reserves)) k) amount),
          dk: amount
        }))

(define-read-only (get-reserves-quote)
    (let (
        (reserves (get-reserves))
        (supply (ft-get-supply ${params.lpTokenSymbol})))
        {
          dx: (get a reserves),
          dy: (get b reserves),
          dk: supply
        }))

;; --- Initialization ---
(begin
    ;; Set token URI
    (var-set token-uri (some u"https://charisma-metadata.vercel.app/api/v1/metadata/<CONTRACT_PRINCIPAL>"))
)
`;

    // Sanitize variable names, remove spaces
    const sanitizedName = params.poolName.replace(/\s+/g, '-').toLowerCase();
    const filename = `${sanitizedName}-subnet-pool.clar`;

    return { code, filename };
} 