import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** One sidebar per section, generated from its folder */
const sidebars: SidebarsConfig = {
  dexSidebar: [{ type: 'autogenerated', dirName: 'dex-api' }],
  blazeSidebar: [{ type: 'autogenerated', dirName: 'blaze-api' }],
  dexteritySidebar: [{ type: 'autogenerated', dirName: 'dexterity' }],
  pricesSidebar: [{ type: 'autogenerated', dirName: 'prices' }],
  dataApisSidebar: [{ type: 'autogenerated', dirName: 'data-apis' }],
  tokenomicsSidebar: [{ type: 'autogenerated', dirName: 'tokenomics' }],
};

export default sidebars;
