export const CHARISMA_TOKEN_SUBNET = "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-token-subnet-v1";
export const RESERVES_PRIVATE_KEY = process.env.PRIVATE_KEY;
export const BLAZE_SIGNER_PRIVATE_KEY = process.env.BLAZE_SIGNER_PRIVATE_KEY;
export const BLAZE_SIGNER_CONTRACT_ID = "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.blaze-v1";