name: Deploy PartyKit

on:
  push:
    branches: [main]
    paths:
      - 'apps/charisma-party/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/charisma-party/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build workspace packages
        run: pnpm build --filter="@repo/*"

      - name: Build charisma-party
        run: pnpm build
        working-directory: ./apps/charisma-party

      - name: Deploy to PartyKit (Production)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          # Set PartyKit token from secrets
          export PARTYKIT_LOGIN="${{ secrets.PARTYKIT_LOGIN }}"
          export PARTYKIT_TOKEN="${{ secrets.PARTYKIT_TOKEN }}"
          
          # Deploy to PartyKit
          echo "🚀 Deploying to PartyKit production..."
          npx partykit deploy
          
          # Wait a moment for deployment to initialize
          sleep 5
          
          # Tail logs to verify deployment initialization
          echo "📋 Tailing PartyKit logs to verify deployment..."
          timeout 30 npx partykit tail --name charisma-party || echo "✅ Deployment completed, log tailing timed out as expected"
        working-directory: ./apps/charisma-party

      - name: Deploy to PartyKit (Preview)
        if: github.event_name == 'pull_request'
        run: |
          # Set PartyKit token from secrets
          export PARTYKIT_TOKEN="${{ secrets.PARTYKIT_TOKEN }}"
          
          # Deploy preview with PR number
          PREVIEW_NAME="charisma-party-pr-${{ github.event.number }}"
          echo "🚀 Deploying PartyKit preview: $PREVIEW_NAME"
          npx partykit deploy --name "$PREVIEW_NAME"
          
          # Wait a moment for deployment to initialize
          sleep 5
          
          # Tail logs to verify deployment initialization
          echo "📋 Tailing PartyKit logs to verify preview deployment..."
          timeout 30 npx partykit tail --name "$PREVIEW_NAME" || echo "✅ Preview deployment completed, log tailing timed out as expected"
          
          # Add PR comment with preview URL
          echo "🔗 Preview deployed at: https://$PREVIEW_NAME.partykit.dev"
        working-directory: ./apps/charisma-party